sec = float(input("Enter time in seconds: "))
mili = sec * (10 ** 3)
micro = sec * (10 ** 6)
nano = sec * (10 ** 9)
pico = sec * (10 ** 12)
femto = sec * (10 ** 15)
print ("Your given times is: ")
print ("Seconds: ", sec)
print ("Miliseconds: ", mili)
print ("Microseconds: ", micro)
print ("Nanoseconds: ", nano)
print ("Picoseconds: ", pico)
print ("Femtoseconds: ", femto)